from calculate_mean_and_variance import calculate_mean_and_variance
from curve_fit_mu_and_var import curve_fit_mu_and_var

#calculate_mean_and_variance(states_matrix, initial_failures)
calculate_mean_and_variance(states_matrix='states', initial_failures='initial_failures', cluster_info = 'cluster_branch_118') #This uses the example fully-generated and bug-free IEEE118 states matrix and initial failures for mu and variance testing
#map_T(number_of_lines, states_matrix, initial_failures)
#takes states_df_simple generated by calculate_mean_and_variance and curve-fits previous mu and var to next state mu and var (when next state available)
curve_fit_mu_and_var()
